[tool.poetry]
name = "tsp"
version = "0.0.7"
description = "`tsp` is a package for Traveling Salesman Problem for Python."
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
homepage = "https://github.com/SaitoTsutomu/tsp"
classifiers = [
   "Development Status :: 1 - Planning",
   "License :: OSI Approved :: Python Software Foundation License",
   "Programming Language :: Python",
   "Topic :: Software Development",
   "Topic :: Scientific/Engineering",
]
license = "PSFL"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
pulp = "^2.1"
more-itertools = "^8.2.0"
numpy = "^1.18.2"
pandas = "^1.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
black = "^19.10b0"
isort = "^4.3.21"
mypy = "^0.770"
ortoolpy = "^0.2.31"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
